#!/bin/bash

pacman -Sy --noconfirm
pacman -S nodejs --noconfirm
pacman -S npm --noconfirm
pacman -S git --noconfirm
git clone https://github.com/skimbledevs/archlinode
cd archlinode
npm install --save
node src/archlinode
